'use client'

import { motion } from 'framer-motion'
import { useState } from 'react'
import { mockExports, mockJsonPreview } from '@/lib/mock-data'

export function ExportsScreen() {
  const [expandedCard, setExpandedCard] = useState<number | null>(null)

  return (
    <section className="bg-surface-alt py-24">
      <div className="max-w-7xl mx-auto px-6">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
          className="mb-12"
        >
          <h2 className="text-4xl font-black text-text-primary mb-2">
            Evaluation Outputs
          </h2>
          <div className="inline-block px-3 py-1.5 rounded-lg text-xs font-mono font-semibold mt-4" style={{ backgroundColor: '#E8F4F7', color: '#1D4E5F' }}>
            Generated by: python cli.py scenario-b
          </div>
        </motion.div>

        {/* Folder cards grid */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ staggerChildren: 0.1, delayChildren: 0.1 }}
          className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12"
        >
          {mockExports.map((exportItem, index) => (
            <motion.div
              key={exportItem.id}
              initial={{ opacity: 0, y: 24 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{
                duration: 0.5,
                ease: [0.22, 1, 0.36, 1],
                delay: 0.1 + index * 0.1,
              }}
              className="bg-white border border-border rounded-xl p-6"
            >
              <div className="mb-6 pb-6 border-b border-border">
                <h3 className="text-sm font-mono font-semibold text-text-primary">
                  outputs/scenario_b_iter{exportItem.iteration}/
                </h3>
              </div>

              <div className="space-y-4 mb-6">
                {exportItem.files.map((file) => (
                  <motion.div
                    key={file.name}
                    initial={{ opacity: 0, scale: 0.9 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    viewport={{ once: true }}
                    transition={{
                      duration: 0.3,
                      delay: 0.15 + index * 0.1,
                      ease: [0.34, 1.56, 0.64, 1],
                    }}
                    className="flex items-center justify-between text-sm"
                  >
                    <span className="flex items-center gap-2">
                      <span>📄</span>
                      <span className="font-mono text-text-primary">{file.name}</span>
                    </span>
                    {file.saved && (
                      <span
                        className="px-2 py-1 rounded text-xs font-semibold"
                        style={{ backgroundColor: '#DCFCE7', color: '#166534' }}
                      >
                        ✓ Saved
                      </span>
                    )}
                  </motion.div>
                ))}
              </div>

              <motion.button
                whileHover={{ y: -2 }}
                whileTap={{ scale: 0.98 }}
                onClick={() =>
                  setExpandedCard(expandedCard === exportItem.id ? null : exportItem.id)
                }
                className="w-full px-4 py-2 border-2 border-teal-primary text-teal-primary font-semibold rounded-lg transition-all hover:bg-teal-light"
              >
                Preview JSON
              </motion.button>

              {/* JSON Preview */}
              {expandedCard === exportItem.id && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  transition={{ duration: 0.3 }}
                  className="mt-6 pt-6 border-t border-border"
                >
                  <pre
                    className="p-4 rounded-lg text-xs overflow-x-auto"
                    style={{
                      backgroundColor: '#1A1A1A',
                      color: '#E5E7EB',
                      fontFamily: 'JetBrains Mono, monospace',
                      lineHeight: '1.5',
                    }}
                  >
                    {JSON.stringify(mockJsonPreview, null, 2)}
                  </pre>
                </motion.div>
              )}
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  )
}
